id: I84D237D1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T17:07:51+00:00'
last_modified: '2022-06-10T08:57:19.624425+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5761
  title: བོད་ཀྱི་དེབ་ཐེར་དཔྱིད་ཀྱི་རྒྱལ་མོའི་གླུ་དབྱངས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ED2A:
      image_group_id: I1KG10661
      title: Volume 1 of rig 'dzin 'ja' tshon snying po'i gter chos yongs rdzogs bka'
        'bum dang bcas pa'i lung gi thog yig skal bzang dad brgya'i pad+mo kun nas
        dgyes pa'i bshes gnyen sogs/
      total_pages: 282
      order: 1
      base_file: ED2A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
